package:
 name: pieparty
 version: "1.5.0"

source:
 #git_url: https://github.com/amcruise/practice_party.git
 path: ..
build:
 #preserve_egg_dir: True
 entry_points:
  - pieparty = pieaparty.__main__:main
 script: python setup.py install
 noarch: generic

host:
 - python

requirements: # includes dependencies
 run: # required packages listed here are automatically installed.

test:
 files: # if any test files are needed
 source_files: # files that are needed and are temporarily copied into test dir

about:
 home: https://github.com/harbourlab/pieparty
 license: MIT
 summary: This is a practice run at building conda packages.
