# test
package:
 name: pieparty
 version: "1.5.2"

source:
 git_url: https://github.com/amcruise/practice_party.git

build:
 preserve_egg_dir: True
 entry_points:
  - pieparty = pieparty.piemain:main
 script: python setup.py install --single-version-externally-managed --record=record.txt
 #noarch: generic
 no_link:
  - pieparty/*.py

requirements: # includes dependencies
 host: # packages required to build the package
  - python
  - setuptools
  - git
 run: # required packages listed here are automatically installed.
  - python
  - matplotlib
  - git

about:
 home: https://github.com/harbourlab/pieparty
 license: MIT
 summary: 
